"""users table

Revision ID: 1f124ca70e55
Revises: 5ab2228c13cc
Create Date: 2022-07-06 03:25:39.844544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f124ca70e55'
down_revision = '5ab2228c13cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_name', sa.String(length=64), nullable=True),
    sa.Column('quiz_writer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_writer'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_quiz_name'), 'quiz', ['quiz_name'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=128), nullable=True),
    sa.Column('correct_answer', sa.String(length=128), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_correct_answer'), 'questions', ['correct_answer'], unique=False)
    op.create_index(op.f('ix_questions_question'), 'questions', ['question'], unique=False)
    op.create_table('sumitted_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_answer', sa.String(length=64), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('submitted_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['submitted_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sumitted_answers_submitted_answer'), 'sumitted_answers', ['submitted_answer'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sumitted_answers_submitted_answer'), table_name='sumitted_answers')
    op.drop_table('sumitted_answers')
    op.drop_index(op.f('ix_questions_question'), table_name='questions')
    op.drop_index(op.f('ix_questions_correct_answer'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_quiz_quiz_name'), table_name='quiz')
    op.drop_table('quiz')
    # ### end Alembic commands ###
