"""submittedanswers table

Revision ID: 336182100b77
Revises: 8a6a3a1509c2
Create Date: 2022-07-06 03:48:25.403234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336182100b77'
down_revision = '8a6a3a1509c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submitted_answers', sa.Column('submitted_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'submitted_answers', 'users', ['submitted_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submitted_answers', type_='foreignkey')
    op.drop_column('submitted_answers', 'submitted_user')
    # ### end Alembic commands ###
