"""users table

Revision ID: 42354f43ce46
Revises: 23f0ed2ae418
Create Date: 2022-07-05 00:23:14.020951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42354f43ce46'
down_revision = '23f0ed2ae418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
