"""users table

Revision ID: 5ab2228c13cc
Revises: 42354f43ce46
Create Date: 2022-07-06 00:10:16.096630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab2228c13cc'
down_revision = '42354f43ce46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_last_seen'), 'users', ['last_seen'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_seen'), table_name='users')
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###
