"""submittedanswers table

Revision ID: 8a6a3a1509c2
Revises: 1f124ca70e55
Create Date: 2022-07-06 03:47:38.443296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6a3a1509c2'
down_revision = '1f124ca70e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submitted_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submittedanswer', sa.String(length=64), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submitted_answers_submittedanswer'), 'submitted_answers', ['submittedanswer'], unique=False)
    op.drop_index('ix_sumitted_answers_submitted_answer', table_name='sumitted_answers')
    op.drop_table('sumitted_answers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sumitted_answers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('submitted_answer', sa.VARCHAR(length=64), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.Column('submitted_user', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['submitted_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sumitted_answers_submitted_answer', 'sumitted_answers', ['submitted_answer'], unique=False)
    op.drop_index(op.f('ix_submitted_answers_submittedanswer'), table_name='submitted_answers')
    op.drop_table('submitted_answers')
    # ### end Alembic commands ###
