"""empty message

Revision ID: d24d9028f643
Revises: 336182100b77
Create Date: 2022-07-06 03:52:21.786798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24d9028f643'
down_revision = '336182100b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_name', sa.String(length=64), nullable=True),
    sa.Column('quiz_writer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_writer'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_quiz_name'), 'quiz', ['quiz_name'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=128), nullable=True),
    sa.Column('correct_answer', sa.String(length=128), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_correct_answer'), 'questions', ['correct_answer'], unique=False)
    op.create_index(op.f('ix_questions_question'), 'questions', ['question'], unique=False)
    op.create_table('submitted_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submittedanswer', sa.String(length=64), nullable=True),
    sa.Column('submitted_user', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['submitted_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submitted_answers_submittedanswer'), 'submitted_answers', ['submittedanswer'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submitted_answers_submittedanswer'), table_name='submitted_answers')
    op.drop_table('submitted_answers')
    op.drop_index(op.f('ix_questions_question'), table_name='questions')
    op.drop_index(op.f('ix_questions_correct_answer'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_quiz_quiz_name'), table_name='quiz')
    op.drop_table('quiz')
    # ### end Alembic commands ###
